#include "tools/nr.h"
#include "tools/nrutil.h"

#include "tools/nrutil.c"
#include "tools/irbit1.c"
#include "tools/metrop.c"
#include "tools/ran3.c"
#include "tools/revcst.c"
#include "tools/trncst.c"
#include "tools/trnspt.c"
#include "tools/select.c"
#include "tools/anneal.c"
#include "tools/reverse.c"
#include "tools/fmin.c"
#include "tools/save_tex.c"
